/*
-----------------------------------------------------------------------------
Filename:    OgreApp2.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.8.x Application Wizard for VC10 (May 2012)
      https://bitbucket.org/jacmoe/ogreappwizards
-----------------------------------------------------------------------------
*/
#ifndef __OgreApp2_h_
#define __OgreApp2_h_

#include "BaseApplication.h"
#include "MonsterCharacterController.h"
#include "PlayerCharacterController.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif


class OgreApp2 : public BaseApplication
{
public:
    OgreApp2(void);
    virtual ~OgreApp2(void);
	 // Ogre::FrameListener
    virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt );
    // OIS::KeyListener
    virtual bool keyPressed( const OIS::KeyEvent& evt );
    virtual bool keyReleased( const OIS::KeyEvent& evt );
    // OIS::MouseListener
    virtual bool mouseMoved( const OIS::MouseEvent& evt );
    virtual bool mousePressed( const OIS::MouseEvent& evt, OIS::MouseButtonID id );
    virtual bool mouseReleased( const OIS::MouseEvent& evt, OIS::MouseButtonID id );
	//player;
	void setupPlayerContent();
	void cleanupPlayerContent();
protected:
    virtual void createScene(void);
private:
	//Ogre::AnimationState *mAnimationState;
	//Ogre::AnimationState *mAnimationState1;
	PlayerCharacterController* mPlayer;
	MonsterCharacterController* mMonster;
	//Overlay * pMyOverlayLogo;
};

#endif // #ifndef __OgreApp2_h_
